### ISSUE TITLE
Button is not showing on Chrome 80.0.3987.149

### ISSUE THREAD

**Issue by mathi-ryte** [hanrok/jiraDone#1]
There is sadly no button showing in Chrome 80.0.3987.149 in Jira Backlog and the JiraDone button is grey

**Comment by mathi-ryte** [comment]
Nevermind I had to toggle it off and on again and now it works

**Comment by mathi-ryte** [comment]
The issue persist when I am reloading it wwill not show the button anymore and I have to switch plugin on and off again

**Comment by hanrok** [comment]
Yes I get it too,
I think it happens only when you navigate within Jira app, if you refresh the page you'll see the button again.
I'll investigate it to see if Chrome extension can notify on in-app client-side navigation.

**Comment by hanrok** [comment]
hi, just pushed a fix for that issue, will update the extension in Chrome store later (https://github.com/hanrok/jiraDone/pull/2)
